### ISSUE TITLE
Parentheses, Brackets and Braces

### ISSUE THREAD

**Issue by nerdinand** [rubymonstas-zurich/slides.rubymonstas.ch#11]
We should add a repetition slide set for after Arrays and Hashes that repeats the use of all the parentheses, brackets and braces. 
![IMG_9543](https://user-images.githubusercontent.com/113440/68607788-be7ff200-04b1-11ea-9c78-f0375162164d.JPG)
![IMG_9544](https://user-images.githubusercontent.com/113440/68607790-be7ff200-04b1-11ea-9f90-442f89dc93d6.JPG)
![IMG_9545](https://user-images.githubusercontent.com/113440/68607791-be7ff200-04b1-11ea-84fd-8c80f293c255.JPG)
![IMG_9546](https://user-images.githubusercontent.com/113440/68607792-be7ff200-04b1-11ea-8520-6d613b42c463.JPG)

**Comment by crackofdusk** [comment]
Addressed in https://github.com/rubymonstas-zurich/rubymonstas-zurich.github.io/pull/13
