### ISSUE TITLE
"More on Strings" Slideset for Session 3

### ISSUE THREAD

**Issue by lxxxvi** [rubymonstas-zurich/slides.rubymonstas.ch#19]
We should have a small slideset for "More on Strings", it should cover

* String interpolation
* `\n`, `\r`, `\t`, etc

**Comment by nerdinand** [comment]
I really wonder if it's worth explaining the escape sequences at all. You don't encounter them very often, except for when using `gets` and we could work around that by just teaching them to use `gets.chomp` always.

WDYT, @hharen @lxxxvi ?
