### ISSUE TITLE
`gets` vs. `gets.chomp`

### ISSUE THREAD

**Issue by nerdinand** [rubymonstas-zurich/slides.rubymonstas.ch#21]
Obviously `gets` vs. `gets.chomp` leads to all sorts of confusion. Maybe it would be better to only ever show `gets` in combination with `chomp`?

WDYT, @lxxxvi @hharen @nethad @crackofdusk?

**Comment by hharen** [comment]
In which lesson is this? If ist's really at the beginning, this would be a reasonable step. 

Generally, I find that quite good to understand that these are two different methods. Maybe start with gets, add chomp and show chomp also with different methods?

**Comment by nerdinand** [comment]
In lesson 2 we have a slideset about "puts and gets". I think it makes sense to "lie" here and just say `gets.chomp` is what everyone should be doing. Only maybe when the question is asked, or in a later session, I'd explain what `chomp` does...

**Comment by hharen** [comment]
yep.

email: h.harencarova@gmail.com
website: seionline.ch
website: momslearntocode.com
mobile CH: +41 78 737 32 33
mobile SK: +421 915 579 068
