### ISSUE TITLE
Add slides about variable scope to "writing methods" slides

### ISSUE THREAD

**Issue by nerdinand** [rubymonstas-zurich/slides.rubymonstas.ch#79]
Something like the following (from session 11 "classes" slides) should be added to the "writing methods" slides as an interactive part (the solutions are revealed one after the other, participants can guess).

![Screenshot 2020-12-21 at 20 04 26](https://user-images.githubusercontent.com/113440/102812762-e5546b80-43c7-11eb-8152-29a1b2a6e0cd.png)

**Comment by lxxxvi** [comment]
Closed by #85
