### ISSUE TITLE
Replace RSS lesson with JSON API

### ISSUE THREAD

**Issue by nerdinand** [rubymonstas-zurich/slides.rubymonstas.ch#82]
RSS is quite unrelatable nowadays and JSON APIs are way more widely used and useful. Therefore we should replace this lesson.

Tasks

* [x] Add slides for JSON (this repo)
* [x] Add exercise(s) for JSON (new repo)
* [x] Replace RSS lesson with JSON slides/exercises (website repo)
* [x] Cleanup, Remove RSS stuff

**Comment by lxxxvi** [comment]
Note to self: Maybe an exercise with https://restcountries.eu ?

**Comment by nerdinand** [comment]
@lxxxvi just found this long list of APIs that are more or less free and open to use: https://github.com/public-apis/public-apis

**Comment by lxxxvi** [comment]
Done

https://github.com/rubymonstas-zurich/rubymonstas-zurich.github.io/pull/66
https://github.com/rubymonstas-zurich/travel-agency-json-exercise/pull/2
https://github.com/rubymonstas-zurich/slides.rubymonstas.ch/pull/89
